### ISSUE TITLE
Naming convention clarification required for cpuUsageArray in ATnT eval library

### ISSUE THREAD

**Issue by goyalvishal** [att/evel-library#11]
As per AttServiceSpecification-VendorEventListener-v2.12.docx cpuUsageArray should have following attributes : cpuIdentifer & percentUsage.

4.6	Datatype: cpuUsage
The cpuUsage datatype consists of the following fields:
Field	Type	Required?	Description
cpuIdentifer	string	Yes	CPU Identifier
percentUsage	number	Yes	CPU usage in percent

But current ATnT eval library is printing following attributes for cpuUsageArray  : Name & Value 

            "cpuUsageArray": [
                {
                    "**name**": "cpu4",
                    "**value**": 76.6
                },

Kindly Clarify.
Thanks.

**Comment by PelagicGames** [comment]
The code is wrong in evel_scaling_measurement.c (lines 708 and 710).

**Comment by miraj** [comment]
This issue is fixed now:
 "cpuUsageArray": [
                {
                    "cpuIdentifier": "cpu0",
                    "percentUsage": 0.0
                },

**Comment by goyalvishal** [comment]
Attributes reported correctly in the latest evel-library version.         
   "cpuUsageArray": [
                {
                    "cpuIdentifier": "cpu0",
                    "percentUsage": 8.0
                },
                {
                    "cpuIdentifier": "cpu1",
                    "percentUsage": 0.0
                },
                {
                    "cpuIdentifier": "cpu2",
                    "percentUsage": 0.0
                },
                {
                    "cpuIdentifier": "cpu3",
                    "percentUsage": 0.0
                }
            ],
