### ISSUE TITLE
Secondary Event Listeners 

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#17]
Hi
Does evel-library has provision to configure secondary event listener (Or test collector)? so that when primary event listener is not reachable all the events can be sent to secondary event listener. 

If this feature is not available, is there any way by which application can be notified that event has not reached test collector so that application can terminate current connection and re-initialize evel-library with second test collector?

**Comment by PelagicGames** [comment]
The current code does not allow provisioning of a secondary event listener within evel-library itself, although it may be possible to run two separate threads, each with a connection to an event listener, and have some external logic for determining which to use.

You may instead want to use a virtual IP/shared domain for your event listeners, with requests being routed to the active event listener, which keeps things simpler on the evel-library side.

`evel_post_api` has return codes for various errors, but the public version of evel-library simply outputs debug logs. You may want to introduce specific handling for these errors in your local copy.

**Comment by patwardhan22** [comment]
Thanks, is there a future plan to support this in evel-library itself?

**Comment by PelagicGames** [comment]
Good question (I wouldn't know).
