### ISSUE TITLE
syslog

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#18]
Evel library supports syslog, when application generates large number of syslogs and redirected to evel library how capable evel library is to handle this?
Is there any design constraints on evel-library about rate at which it can process and forward syslogs to test collector?.
If there are lots of syslogs redirected to evel library will it effect other events (faults, measurement, heartbeat etc )?
Is there any limit on size of syslog string which it can process / forward at a time?

**Comment by PelagicGames** [comment]
[EVEL_EVENT_BUFFER_DEPTH](https://github.com/att/evel-library/blob/master/code/evel_library/evel.h#L119) defines the size of the ring buffer used by evel-library to hold events before they are sent to the collector. As per the comments, this value should be tuned to handle bursts of events. However, that will not help if syslog events are raised faster than they are POSTed. If the ring buffer is full when `ring_buffer_write` is called then the new event will be dropped (regardless of event type, so lots of syslogs may cause faults/measurements/heartbeats to be dropped).

There is no explicit size limit for syslog strings, but exceptionally long strings could theoretically cause memory issues. If you hit such issues, you may want to consider splitting events into multiple parts (if that's applicable).

How large are you expecting your syslog strings to be (order of magnitude)?
