### ISSUE TITLE
topicName : should it be an argument from the ECOMP Admin

### ISSUE THREAD

**Issue by miraj** [att/evel-library#5]
is topicName a one time argument from ECOMP Admin? 
Give an example Topic Name

**Comment by PelagicGames** [comment]
topicName is part of the URL used in POST requests, and it specifies the specific event topic which the body of the request contains (relevant to the publishSpecificTopic operation action).

The topicName is equivalent to the eventType field in commonEventHeader.

An example would be something like Fault_MobileCallRecording_PilotNumberPoolExhaustion.

**Comment by miraj** [comment]
I can specify the topicName only at the time of initialisation. Why can't I specify it while creating the CommonEventHeader? Because I call initialisation function once only and will end up creating & sending different types of Events (eg: Fault & Measurement).

**Comment by PelagicGames** [comment]
If you are only ever POSTing a specific event then you would use the publishSpecificTopic operation action. If you are POSTing multiple event types (even if they are sent one at a time) then you should probably use the publishAnyEvent operation action, for which the URL format is /eventListener/v{apiVersion} (i.e. there is no topicName).

Does that help?

**Comment by miraj** [comment]
Makes sense.

**Comment by miraj** [comment]
We decided to use publishAnyEvent
