### ISSUE TITLE
fault Fields Version

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#6]
As per "ATT Events API Details Doc.docx", one of the fault fields is "faultFieldsVersion".
But in evel library code I don't see this field. Fault has only below fields

typedef struct event_fault {
  EVENT_HEADER header;
  DLIST additional_info;
  char * alarm_condition;
  char * alarm_interface_a;
  EVEL_FAULT_SEVERITIES event_severity;
  EVEL_SOURCE_TYPES event_source_type;
  char * specific_problem;
  EVEL_VF_STATUSES vf_status;
} EVENT_FAULT;

**Comment by miraj** [comment]
New version has this structure:
typedef struct event_fault {
  /***************************************************************************/
  /* Header and version                                                      */
  /***************************************************************************/
  EVENT_HEADER header;
  int major_version;
  int minor_version;

  /***************************************************************************/
  /* Mandatory fields                                                        */

  /***************************************************************************/
  EVEL_SEVERITIES event_severity;
  EVEL_SOURCE_TYPES event_source_type;
  char * alarm_condition;
  char * specific_problem;
  EVEL_VF_STATUSES vf_status;

  /***************************************************************************/
  /* Optional fields                                                         */
  /***************************************************************************/
  EVEL_OPTION_STRING alarm_interface_a;
  DLIST additional_info;

} EVENT_FAULT;
