### ISSUE TITLE
Measurement event fields 

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#8]
As per "AttServiceSpecification-VendorEventListener-v2.12.docx"
In Measurement events fields "configuredEntities " & "meanRequestLatency" are not required.
But these fields are mandatory parameters for "evel_new_measurement()" API.

EVENT_MEASUREMENT * evel_new_measurement(int concurrent_sessions,
                                         int configured_entities,
                                         double mean_request_latency,
                                         double measurement_interval,
                                         double memory_configured,
                                         double memory_used,
                                         int request_rate)

**Comment by miraj** [comment]
"configuredEntities " & "meanRequestLatency" are no longer mandatory arguments
