### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by patwardhan22** [att/evel-library#9]
Hi
Communication between evel-library and test collector works fine with 'http' protocol.
But when 'https' is enabled in evel-library, test collector can not decode the message and dumps garbage value.
Not sure its issue with evel-library or Test collector.

**Comment by PelagicGames** [comment]
The problem is with evel-test-collector. You'll need to add HTTPS support to the wsgiref server, for example using `httpd.socket = ssl.wrap_socket(httpd.socket, certfile=<path-to-cert-file>, server_side=True)` when running in secure mode

**Comment by patwardhan22** [comment]
thanks.. I will try this and update the result.

**Comment by miraj** [comment]
This is a test collector problem. Issue added in the test collectory project:
https://github.com/att/evel-test-collector/issues/3
